CREATE TABLE IF NOT EXISTS admins (id SERIAL PRIMARY KEY, username VARCHAR(100) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS students (id SERIAL PRIMARY KEY, name VARCHAR(255) NOT NULL, "group" VARCHAR(50) NOT NULL, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS grades (id SERIAL PRIMARY KEY, student_id INTEGER NOT NULL REFERENCES students(id), month VARCHAR(20) NOT NULL, year INTEGER NOT NULL, score INTEGER NOT NULL, created_at TIMESTAMP DEFAULT NOW(), UNIQUE(student_id, month, year));
